import { FaXTwitter, FaGithub, FaInstagram, FaBriefcase } from "react-icons/fa6";
import {
	FcBiomass,
	FcComboChart,
	FcCommandLine,
	FcElectronics,
	FcFlashOn,
	FcGlobe,
	FcNook,
	FcPanorama,
	FcProcess,
	FcPuzzle,
	FcReading,
	FcSettings,
	FcSportsMode,
	FcTodoList,
	FcWorkflow,
} from "react-icons/fc";
import {
	LiaBoltSolid,
	LiaBookOpenSolid,
	LiaBookSolid,
	LiaBriefcaseSolid,
	LiaBugSolid,
	LiaCloudSolid,
	LiaCodeSolid,
	LiaCogSolid,
	LiaCogsSolid,
	LiaCubeSolid,
	LiaGithub,
	LiaGlobeSolid,
	LiaHandshake,
	LiaHashtagSolid,
	LiaInfoCircleSolid,
	LiaKeyboardSolid,
	LiaLaptopCodeSolid,
	LiaLightbulb,
	LiaNpm,
	LiaPaletteSolid,
	LiaPeopleCarrySolid,
	LiaPlugSolid,
	LiaRocketSolid,
	LiaSearchSolid,
	LiaSketch,
	LiaStarOfLifeSolid,
	LiaTerminalSolid,
	LiaUser,
	LiaUserFriendsSolid,
	LiaUserTieSolid,
	LiaWhmcs,
} from "react-icons/lia";
import { MdOutlineArrowForward, MdOutlineArrowOutward } from "react-icons/md";

/**
 * Defines the available icon names and their corresponding React components.
 * This mapping allows for easy reference and usage of icons throughout the application.
 */
export type IconName = keyof typeof ICONS;

/**
 * A constant object that maps icon names to their corresponding React components.
 * This allows for easy retrieval and usage of icons based on their names.
 */
export const ICONS = {
	bolt: LiaBoltSolid,
	book: LiaBookSolid,
	bookOpen: LiaBookOpenSolid,
	briefCase: LiaBriefcaseSolid,
	bug: LiaBugSolid,
	cloud: LiaCloudSolid,
	code: LiaCodeSolid,
	cog: LiaCogSolid,
	cogs: LiaCogsSolid,
	cube: LiaCubeSolid,
	gears: LiaWhmcs,
	github: LiaGithub,
	globe: LiaGlobeSolid,
	handShake: LiaHandshake,
	hashtag: LiaHashtagSolid,
	infoCircle: LiaInfoCircleSolid,
	keyboard: LiaKeyboardSolid,
	laptop: LiaLaptopCodeSolid,
	lightBulb: LiaLightbulb,
	npm: LiaNpm,
	palette: LiaPaletteSolid,
	peopleCarry: LiaPeopleCarrySolid,
	plug: LiaPlugSolid,
	rocket: LiaRocketSolid,
	search: LiaSearchSolid,
	sketch: LiaSketch,
	star: LiaStarOfLifeSolid,
	terminal: LiaTerminalSolid,
	user: LiaUser,
	users: LiaUserFriendsSolid,
	userTie: LiaUserTieSolid,

	arrowRight: MdOutlineArrowForward,
	arrowOutward: MdOutlineArrowOutward,

	faBriefcase: FaBriefcase,
	faGithub: FaGithub,
	faInstagram: FaInstagram,
	faXTwitter: FaXTwitter,

	fcBiomass: FcBiomass,
	fcChart: FcComboChart,
	fcCli: FcCommandLine,
	fcElectronics: FcElectronics,
	fcFlash: FcFlashOn,
	fcGlobe: FcGlobe,
	fcNook: FcNook,
	fcPanorama: FcPanorama,
	fcProcess: FcProcess,
	fcPuzzle: FcPuzzle,
	fcReading: FcReading,
	fcRun: FcSportsMode,
	fcSettings: FcSettings,
	fcTodo: FcTodoList,
	fcWorkflow: FcWorkflow,
} as const;
