import { FaXTwitter, FaGithub, FaInstagram, FaBriefcase } from "react-icons/fa6";
import {
	FcBiomass,
	FcComboChart,
	FcCommandLine,
	FcElectronics,
	FcFlashOn,
	FcGlobe,
	FcNook,
	FcPanorama,
	FcProcess,
	FcPuzzle,
	FcReading,
	FcSettings,
	FcSportsMode,
	FcTodoList,
	FcWorkflow,
} from "react-icons/fc";
import {
	LiaAwardSolid,
	LiaBoltSolid,
	LiaBriefcaseSolid,
	LiaBugSolid,
	LiaCalendarCheckSolid,
	LiaCheckCircleSolid,
	LiaCloudSolid,
	LiaCodeSolid,
	LiaCogsSolid,
	LiaCubeSolid,
	LiaDownloadSolid,
	LiaExchangeAltSolid,
	LiaExclamationTriangleSolid,
	LiaExternalLinkSquareAltSolid,
	LiaFileCodeSolid,
	LiaGithub,
	LiaGlobeSolid,
	LiaHandshake,
	LiaHistorySolid,
	LiaIdCardSolid,
	LiaInfoCircleSolid,
	LiaJsSquare,
	LiaKeyboardSolid,
	LiaLaptopCodeSolid,
	LiaLeafSolid,
	LiaLightbulb,
	LiaLinkSolid,
	LiaNpm,
	LiaPaletteSolid,
	LiaPeopleCarrySolid,
	LiaQuestionCircleSolid,
	LiaQuestionSolid,
	LiaRouteSolid,
	LiaSearchSolid,
	LiaSlidersHSolid,
	LiaTerminalSolid,
	LiaToggleOnSolid,
	LiaUserSolid,
	LiaUsersSolid,
	LiaUserTieSolid,
} from "react-icons/lia";
import { MdOutlineArrowForward, MdOutlineArrowOutward } from "react-icons/md";

/**
 * Defines the available icon names and their corresponding React components.
 * This mapping allows for easy reference and usage of icons throughout the application.
 */
export type IconName = keyof typeof ICONS;

/**
 * A constant object that maps icon names to their corresponding React components.
 * This allows for easy retrieval and usage of icons based on their names.
 */
export const ICONS = {
	bolt: LiaBoltSolid,
	briefCase: LiaBriefcaseSolid,
	bug: LiaBugSolid,
	calendarCheck: LiaCalendarCheckSolid,
	checkCircle: LiaCheckCircleSolid,
	cloud: LiaCloudSolid,
	code: LiaCodeSolid,
	cogs: LiaCogsSolid,
	cube: LiaCubeSolid,
	download: LiaDownloadSolid,
	exchange: LiaExchangeAltSolid,
	exclamation: LiaExclamationTriangleSolid,
	externalLink: LiaExternalLinkSquareAltSolid,
	fileCode: LiaFileCodeSolid,
	github: LiaGithub,
	globe: LiaGlobeSolid,
	handShake: LiaHandshake,
	history: LiaHistorySolid,
	idCard: LiaIdCardSolid,
	infoCircle: LiaInfoCircleSolid,
	keyboard: LiaKeyboardSolid,
	laptop: LiaLaptopCodeSolid,
	leaf: LiaLeafSolid,
	lightBulb: LiaLightbulb,
	link: LiaLinkSolid,
	npm: LiaNpm,
	palette: LiaPaletteSolid,
	peopleCarry: LiaPeopleCarrySolid,
	question: LiaQuestionSolid,
	questionCircle: LiaQuestionCircleSolid,
	route: LiaRouteSolid,
	search: LiaSearchSolid,
	sliders: LiaSlidersHSolid,
	terminal: LiaTerminalSolid,
	user: LiaUserSolid,
	users: LiaUsersSolid,
	userTie: LiaUserTieSolid,
	toggleOn: LiaToggleOnSolid,
	jsSquare: LiaJsSquare,
	award: LiaAwardSolid,

	arrowRight: MdOutlineArrowForward,
	arrowOutward: MdOutlineArrowOutward,

	faBriefcase: FaBriefcase,
	faGithub: FaGithub,
	faInstagram: FaInstagram,
	faXTwitter: FaXTwitter,

	fcBiomass: FcBiomass,
	fcChart: FcComboChart,
	fcCli: FcCommandLine,
	fcElectronics: FcElectronics,
	fcFlash: FcFlashOn,
	fcGlobe: FcGlobe,
	fcNook: FcNook,
	fcPanorama: FcPanorama,
	fcProcess: FcProcess,
	fcPuzzle: FcPuzzle,
	fcReading: FcReading,
	fcRun: FcSportsMode,
	fcSettings: FcSettings,
	fcTodo: FcTodoList,
	fcWorkflow: FcWorkflow,
} as const;
