/**
 * IndexNow Script
 *
 * Submits URLs from sitemap to IndexNow API for search engine indexing.
 *
 * Usage:
 *   bun run indexnow - Submit URLs to IndexNow
 */

import fs from 'fs/promises';
import path from 'path';

import ora from 'ora';
import xml2js from 'xml2js';

// The public site URL used to derive host and key location for IndexNow.
const SITE_URL = 'https://veganipsum.vercel.app';
// IndexNow key (published as a verification file at SITE_URL/<KEY>.txt).
const KEY = '91c80f732f4e4e5b80b4c02a7e8c9e9c';
const KEY_LOCATION = SITE_URL + '/' + KEY + '.txt';
// Local path to the sitemap file generated by the Next.js build.
const SITEMAP_PATH = path.resolve(process.cwd(), 'public', 'sitemap-0.xml');
// Number of URLs to submit per IndexNow request (API suggests batching).
const CHUNK_SIZE = 100;

/**
 * Reads the sitemap file from disk.
 *
 * @param {string} sitemapPath - Absolute path to the sitemap XML file.
 *
 * @returns {Promise<string>} The raw sitemap XML content.
 */
async function readSitemapFile(sitemapPath: string): Promise<string> {
  return await fs.readFile(sitemapPath, 'utf8');
}

/**
 * Parses a sitemap XML string into an array of URL strings.
 *
 * @param {string} xmlContent - The raw sitemap XML content.
 *
 * @returns {string[]} Extracted URL strings from the sitemap.
 */
async function parseSitemapUrls(xmlContent: string): Promise<string[]> {
  const parsed: { urlset?: { url?: Array<{ loc?: string[] }> } } = await xml2js.parseStringPromise(xmlContent);

  const urls = parsed.urlset?.url?.map((entry) => entry.loc?.[0]).filter(Boolean) as string[] | undefined;

  return urls ?? [];
}

/**
 * Submits a chunk of URLs to the IndexNow API.
 *
 * @param {string[]} urlChunk - Array of URLs to submit.
 *
 * @returns {Promise<{ ok: boolean; message: string }>} Result of the submission.
 */
async function submitIndexNowChunk(urlChunk: string[]): Promise<{ ok: boolean; message: string }> {
  const response = await fetch('https://api.indexnow.org/indexnow', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ host: new URL(SITE_URL).host, key: KEY, keyLocation: KEY_LOCATION, urlList: urlChunk }),
  });

  if (response.ok) {
    return { ok: true, message: `Submitted ${urlChunk.length} URLs` };
  }

  const errorText = await response.text();
  return { ok: false, message: `Failed: ${errorText}` };
}

/**
 * Submits sitemap URLs to IndexNow in chunks for faster search engine indexing.
 *
 * @param {string[]} urls - Array of URLs to submit.
 * @param {ReturnType<typeof ora>} spinner - Loading spinner for progress indication.
 *
 * @returns {Promise<void>} Resolves when all URL chunks have been processed.
 */
async function submitChunks(urls: string[], spinner: ReturnType<typeof ora>): Promise<void> {
  for (let i = 0; i < urls.length; i += CHUNK_SIZE) {
    const chunk = urls.slice(i, i + CHUNK_SIZE);
    spinner.start('Submitting URLs ' + (i + 1) + ' to ' + Math.min(i + CHUNK_SIZE, urls.length));

    const result = await submitIndexNowChunk(chunk);

    if (result.ok) {
      spinner.succeed(result.message);
    } else {
      spinner.fail(result.message);
    }
  }
}

async function main(): Promise<void> {
  const spinner = ora('Reading sitemap...').start();

  // Read the sitemap file produced by the site build.
  let sitemapContent: string;
  try {
    sitemapContent = await readSitemapFile(SITEMAP_PATH);
  } catch {
    spinner.fail('Sitemap file not found: ' + SITEMAP_PATH);
    process.exit(1);
  }

  // Parse the sitemap XML into a list of URLs.
  let urls: string[];
  try {
    urls = await parseSitemapUrls(sitemapContent);
  } catch {
    spinner.fail('Failed to parse sitemap XML');
    process.exit(1);
  }

  if (urls.length === 0) {
    spinner.warn('No URLs found in sitemap');
    process.exit(0);
  }

  spinner.succeed('Found ' + urls.length + ' URLs');

  // Submit URLs in chunks to avoid overly large payloads.
  await submitChunks(urls, spinner);

  // Final status message.
  ora('All URLs processed!').succeed();
}

main().catch((error) => {
  console.error('Error:', error);
  process.exit(1);
});
